[package]
name = "nvflex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
unsafe_send_sync = []

[dependencies]
bitflags = "2.4.0"
nvflex-sys = { path = "../nvflex-sys" }
